// Implements a dictionary's functionality

#include <ctype.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include "dictionary.h"

int wordcount = 0;

//define node struct, rename simply "node"
typedef struct node
{
    char word[LENGTH + 1];
    struct node *next;
}
node;

node *cursor;

//create hashtable using previously declared "node" struct
node *hashtable[26];

/*
Declare hash function - this function will correct for case,
then return an int that corresponds with where the first letter
of the word falls alphabetically.
Source: This hash function is based on info from CS50 Study https://study.cs50.net/hashtables
 as well as the corresponding video found at https://www.youtube.com/watch?v=h2d9b_nEzoA
*/
int hash(const char *word)
{
    int hash = (tolower(word[0]) - 'a');
    return hash;

}

// CHECK returns true if word is in dictionary else false
bool check(const char *word)
{
    char wordcheck[LENGTH + 1];

    strcpy(wordcheck, word);

    for (int i = 0; i < strlen(wordcheck); i++)
    {
        wordcheck[i] = tolower(wordcheck[i]);
    }

    int hashkey = hash(wordcheck);

    node *head = hashtable[hashkey];

    cursor = head;

    while (cursor != NULL)
    {
        if (strcasecmp(wordcheck, cursor->word) == 0)
        {
            return true;
        }
        else
        {
            cursor = cursor->next;
        }
    }

    //if word is not found in dictionary
    return false;
}

// LOAD loads dictionary into memory, returning true if successful else false
bool load(const char *dictionary)
{
    char word[LENGTH + 1];

    FILE *dict = fopen(dictionary, "r");
    if (dict == NULL)
    {
        fprintf(stderr, "Could not open Dictionary");
        return false;
    }

    /* -MAKE NEW WORD- use "fscanf" to scan through file(dictionary) for a string, put that string in the variable "word". Execute loop
    until end of dictionary file*/
    while (fscanf(dict, "%s", word) != EOF)
    {
        //malloc a node * for new word
        node *new_node = malloc(sizeof(node));
        new_node->next = NULL;

        //if pointer to node returns NULL, unload dictionary and quit Speller
        if (new_node == NULL)
        {
            unload();
            return false;
        }
        //copy word into node
        strcpy(new_node->word, word);

        //int "hashvalue" gets the hash value generated by hash function for (word)
        int hashvalue = hash(word);

        //if this bucket in the "hashtable" array  has not been assigned a node yet, simply add "new_node"
        if (hashtable[hashvalue] == NULL)
        {
            hashtable[hashvalue] = new_node;
        }

        //else, add "new_node" to the list of values stored at this bucket in the array
        else
        {
            /*
            point "new_node->next" to the pointer that "hashtable[hashvalue]" is currently pointing to
            (now the "new_node->next" pointer and the "hashtable[hashvalue]" pointer are both pointing to
            the old "first" node in the list)
            */
            new_node->next = hashtable[hashvalue];

            //now we can safely point "hashtable[hashvalue]" to the new(est) node in our list, thus inserting it in front of the node that was previously first in the list.
            hashtable[hashvalue] = new_node;

        }

        wordcount++;
    }

    fclose(dict);

    //when finished:
    return true;
}

// SIZE returns number of words in dictionary if loaded else 0 if not yet loaded
unsigned int size(void)
{

    return wordcount;
}

// UNLOAD unloads dictionary from memory, returning true if successful else false
bool unload(void)
{
    for (int i = 0, n = 26; i < n; i++)
    {
        cursor = hashtable[i];

        while (cursor != NULL)
        {
            node *temp = cursor;
            cursor = cursor->next;
            free(temp);
        }

    }

    return true;

    /*
    Add functionality to return false if dictionary fails to unload...
    */

}
